spring.application.name=springboot-api-demo
server.port=8080

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# API Metadata
springdoc.api-docs.title=Workshop Spring Boot API
#pringdoc.api-docs.version=1.0.0
springdoc.api-docs.description=API del taller de Spring Boot - Progra3
springdoc.api-docs.contact.name=Tara Lynn

